# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-04 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_token_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='uid',
            field=models.CharField(default='4b669ba9-772a-4967-866a-acdd243e3034', max_length=40),
        ),
    ]
